name: btl_moblie
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.9.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  #package dung de dieu huong cac man hinh
  go_router: ^14.0.0

  font_awesome_flutter: ^10.12.0
  #package dung de da ngon ngu
  easy_localization: ^3.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  #import thu muc anh de dung anh cho app
  assets:
    - assets/images/
    - assets/icons/
    - assets/lang/

  #import font chu cho app
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
          weight: 500

